plugins {
    id 'java-library'
    id 'maven-publish'
}

// Plugin config
ext.pluginNameUpper = "NyaaPlayerCoser"
ext.pluginNameLower = ext.pluginNameUpper.toLowerCase()
ext.majorVersion = 8
ext.minorVersion = 2
ext.minecraftVersion = "1.21.11"

// Suppiled by Jenkins
ext.buildNumber = System.env.BUILD_NUMBER == null ? "SNAPSHOT" : "$System.env.BUILD_NUMBER"
ext.mavenDirectory = System.env.MAVEN_DIR == null ? "$projectDir/repo" : "$System.env.MAVEN_DIR"
ext.jdDirectory = System.env.JAVADOCS_DIR == null ? null : "$System.env.JAVADOCS_DIR"

// Version used for distribution
group = "cat.nyaa"
archivesBaseName = "${pluginNameUpper}-mc$minecraftVersion"
version = "$majorVersion.$minorVersion.$buildNumber".toString()

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Repositories and dependencies
repositories {
    mavenCentral()
    maven { name 'Paper'; url 'https://repo.papermc.io/repository/maven-public/' }
    maven { name 'NyaaCat'; url 'https://ci.nyaacat.com/maven/' }
    maven { name 'JitPack'; url 'https://jitpack.io' } // ProtocolLib (master)
    maven { name 'aikar'; url 'https://repo.aikar.co/content/groups/aikar/' }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:$minecraftVersion-R0.1-SNAPSHOT"

    // other nyaa plugins
    compileOnly('cat.nyaa:nyaacore:9.10') { transitive = false }

    // 3rd party plugins
    compileOnly('com.github.dmulloy2:ProtocolLib:master-SNAPSHOT') { transitive = false }
}

// source file modification (modify version string)
processResources {
    filesMatching("**/plugin.yml") {
        expand 'version': project.version
    }
}

// source file jar
task sourcesJar(type: Jar) {
    archiveClassifier.set("sources")
    from sourceSets.main.allSource
}

// javadoc generation options
javadoc {
    if (project.jdDirectory != null) destinationDir = file("${jdDirectory}/${pluginNameLower}-${version}")

    (options as StandardJavadocDocletOptions).with {
        links 'https://docs.oracle.com/en/java/javase/21/docs/api/'
        links 'https://jd.papermc.io/paper/1.21/'

        locale 'en_US'
        encoding 'UTF-8'
        docEncoding 'UTF-8'
        addBooleanOption('keywords', true)
        addStringOption('Xdoclint:none', '-quiet')
        options.addBooleanOption('html5', true)

        windowTitle = "${pluginNameUpper} Javadoc"
        docTitle = "${pluginNameUpper} (mc$minecraftVersion-${project.version})"
    }
}

// javadoc jar
task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier.set("javadoc")
    from javadoc.destinationDir
}

// compile options
compileJava {
    options.compilerArgs += ["-Xlint:deprecation"]
}

// maven publish
publishing {
    publications {
        mavenJava(MavenPublication) {
            group project.group
            artifactId pluginNameLower
            version "$majorVersion.$minorVersion-SNAPSHOT"

            from components.java
            artifact sourcesJar
            artifact javadocJar
        }
    }
    repositories {
        maven {
            url mavenDirectory
        }
    }
}
