name: NyaaPlayerCoser
main: cat.nyaa.npc.NyaaPlayerCoser
description: "NPC plugin for NyaaCraft servers"
version: 0.1
depend: [NyaaCore]
softdepend: []
authors: [RecursiveG]
website: "https://github.com/NyaaCat/NyaaPlayerCoser"

commands:
  nyaaplayercoser:
    description: The command for NyaaPlayerCoser
    aliases: npc
    permission: npc.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  npc.command:
    description: Run NPC commands
    default: true

  npc.admin:
    description: Permissions for the god
    default: op
    children:
      npc.command: true
