name: NyaaPlayerCoser
main: cat.nyaa.npc.NyaaPlayerCoser
description: "NPC plugin for NyaaCraft servers"
version: 0.1
depend: [NyaaCore, ProtocolLib]
softdepend: [HamsterEcoHelper]
authors: [RecursiveG]
website: "https://github.com/NyaaCat/NyaaPlayerCoser"
api-version: 1.13

commands:
  nyaaplayercoser:
    description: The command for NyaaPlayerCoser
    aliases: npc
    permission: npc.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  npc.admin:
    description: Permissions for the god
    default: op
    children:
      npc.player: true
      npc.command.inspect: true
      npc.command.import: true
      npc.command.reload: true
      npc.command.skin: true
      npc.command.spawn: true
      npc.command.remove: true
      npc.command.edit: true
  npc.player:
    description: Permissions for players
    default: op
    children:
      npc.command: true
      npc.command.hehshop: true
  npc.interact:
    description: Permission required to interact with NPCs
    default: true
  npc.debug:
    description: Toggle debug flag and more
    default: false
