name: NyaaPlayerCoser
main: cat.nyaa.npc.NyaaPlayerCoser
description: "NPC plugin for NyaaCraft servers"
version: 0.1
depend: [NyaaCore, ProtocolLib]
softdepend: [HamsterEcoHelper]
authors: [RecursiveG]
website: "https://github.com/NyaaCat/NyaaPlayerCoser"
api-version: 1.13

commands:
  nyaaplayercoser:
    description: The command for NyaaPlayerCoser
    aliases: npc
    permission: npc.admin
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  npc.admin:
    description: Permissions for the god
    default: op
    children:
      npc.admin.spawn: true
      npc.admin.info: true
      npc.admin.remove: true
      npc.admin.edit: true
      npc.admin.import: true
      npc.admin.reload: true

  npc.player:
    description: Permissions for players
    default: true
    children:
      npc.player.spawn: true
      npc.player.remove: true
